### ISSUE TITLE
[BUG] Literal Game Breaking Inventory Crafting Bug

### ISSUE THREAD

**Issue by CptZee** [mahjerion/Craft-to-Exile-Harmony#58]
**Technical Specs (please complete the following information):**
 - Craft to Exile Version 1.3.9
 - World Type: Tried in multiplayer and singleplayer
 - RAM Allocation: 8GB

**Describe the bug**
So this bug will crash the server (multiplayer) or crash your client (singleplayer) when you try to craft something using your crafting guide (That green book vanilla mc added)

**To Reproduce**
1. Go to your inventory.
2. Click on green book (Crafting Recipes)
3. Select something
4. Game/Server Crash

**Expected behavior**
Works normally just like how vanilla does it.

**Comment by mahjerion** [comment]
fixed for next update (tomorrow morning) happy new year and thanks

**Comment by CptZee** [comment]
Umm it's not fixed yet.
Now, when you use the book in the portable crafter it will crash...

`[13:43:38] [Server thread/WARN]: @Redirect conflict. Skipping randompatches.mixins.json:InputSlotFillerMixin->@Redirect::getSlotWithUnusedStack(Lnet/minecraft/class_1661;Lnet/minecraft/class_1799;)I with priority 1000, already redirected by nbtcrafting.mixins.json:MixinInputSlotFiller->@Redirect::playerInventoryFindStack(Lnet/minecraft/class_1661;Lnet/minecraft/class_1799;)I with priority 1000
[13:43:38] [Server thread/ERROR]: Encountered an unexpected exception
org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150) ~[fabric-server-launch.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_275]
        at net.minecraft.class_1729.method_17697(class_1729.java:17) ~[intermediary-server.jar:?]
        at net.minecraft.class_3244.method_17820(class_3244.java:1327) ~[intermediary-server.jar:?]
        at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_275]
        at net.minecraft.class_3244.method_12061(class_3244.java:1327) ~[intermediary-server.jar:?]
        at net.minecraft.class_2840.method_12317(class_2840.java:40) ~[intermediary-server.jar:?]
        at net.minecraft.class_2840.method_11054(class_2840.java:10) ~[intermediary-server.jar:?]
        at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-server.jar:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:144) ~[intermediary-server.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:758) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:152) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:118) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:740) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:734) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_18857(class_1255.java:127) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:719) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:254) ~[intermediary-server.jar:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector getSlotWithUnusedStack(Lnet/minecraft/class_1661;Lnet/minecraft/class_1799;)I in randompatches.mixins.json:InputSlotFillerMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap randompatches-refmap.json
        at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:408) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1291) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351) ~[fabric-server-launch.jar:?]
        ... 26 more`

**Comment by mahjerion** [comment]
My bad, I'll take another look. Saw jerbears comment too

**Comment by mahjerion** [comment]
fixed for next udpate
